site_name: IT50

theme:
  language: en
  name: material
  features:
    - navigaion.instant
    - navigation.tabs
    - navigation.indexes

nav:
  - About: en/
  - Theory:
    - en/theory/index.md
    - Data:
      - en/theory/data.md
      - Binary Data: en/theory/binary-data.md
      - Text Encoding: en/theory/text-encoding.md
      - File Format: en/theory/file-format.md
      - Partitioning and Filesystem: en/theory/partitioning-and-filesystem.md
    - Program:
      - en/theory/program.md
    - Cryptography:
      - en/theory/cryptography.md
      - Cryptographic Hash: en/theory/cryptographic-hash.md
      - Symmetric Cryptogtaphy: en/theory/symmetric-cryptography.md
      - Asymmetric Cryptography: en/theory/asymmetric-cryptography.md
      - Public Key Infrastructure: en/theory/public-key-infrastructure.md
    - Network:
      - en/theory/network.md
  - Lab:
    - en/lab/index.md
    - GNU/Linux:
      - en/lab/gnu-linux/index.md
      - Program: en/lab/gnu-linux/program.md
      - Cryptographic Hash: en/lab/gnu-linux/cryptographic-hash.md
    - macOS: en/lab/macos
    - Windows: en/lab/windows

extra:
  homepage: en/
  alternate:
    - name: English
      link: en/
      lang: en
    - name: 中文（简体）
      link: zh-Hans/
      lang: zh

markdown_extensions:
  - extra
  - meta
  - def_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.keys
